// Spanish (source) -> English. Keys are the exact Spanish strings used in the UI;
// {name} placeholders are filled in by t().
export const EN = {
  // ---- Page, header, help menu ----
  'SubnetCraft — Planifica, divide y documenta redes IP': 'SubnetCraft — Plan, split and document IP networks',
  'Planifica, divide y documenta redes IP': 'Plan, split and document IP networks',
  'Logo de SubnetCraft': 'SubnetCraft logo',
  'Divisor visual': 'Visual splitter',
  'Planificador VLSM': 'VLSM planner',
  'Calculadora IPv4': 'IPv4 calculator',
  'Calculadora IPv6': 'IPv6 calculator',
  'Herramientas': 'Tools',
  'Ayuda': 'Help',
  '¿Qué necesitas hacer? Atajos y explicaciones': 'What do you need to do? Shortcuts and explanations',
  '¿Qué necesitas hacer?': 'What do you need to do?',
  'Repartir una red entre áreas': 'Divide a network among departments',
  'Dices cuántos equipos tiene cada VLAN y la app calcula las subredes y la configuración.': 'Tell it how many devices each VLAN has and the app works out the subnets and the configuration.',
  'Dividir una red a mano': 'Split a network by hand',
  'Haz clic para partir una red en mitades y ver el árbol de subredes.': 'Click to cut a network in halves and see the subnet tree.',
  'Saber todo sobre una IP': 'Learn everything about an IP',
  'Red, broadcast, máscara y rango de equipos de una dirección IPv4.': 'Network, broadcast, mask and host range of an IPv4 address.',
  'Empezar con IPv6': 'Get started with IPv6',
  'Si no sabes de prefijos, un plan guiado te da el direccionamiento listo.': 'If you do not know prefixes, a guided plan gives you ready-made addressing.',
  'Comprobar o resumir redes': 'Check or summarize networks',
  '¿Está esta IP en la red?, resumen de rutas, traslapes y conversor de máscaras.': 'Is this IP in the network?, route summarization, overlaps and mask converter.',
  'Cambiar tema claro/oscuro': 'Switch light/dark theme',
  'Cambiar tema': 'Switch theme',
  'Cambiar idioma (español / inglés)': 'Switch language (Spanish / English)',
  'Idioma': 'Language',

  // ---- IPv4 calculator ----
  'Ingresa una IP y su prefijo CIDR o máscara para obtener el desglose completo de la red.': 'Enter an IP and its CIDR prefix or mask to get the full breakdown of the network.',
  'Subredes guardadas': 'Saved subnets',
  'Aún no has guardado ninguna subred. Calcula una y dale a "Guardar".': 'You have not saved any subnet yet. Calculate one and press "Save".',
  'Dirección IP': 'IP address',
  'Máscara o prefijo CIDR': 'Mask or CIDR prefix',
  'VLAN (opcional)': 'VLAN (optional)',
  'Gateway sugerido': 'Suggested gateway',
  'Primera IP útil': 'First usable IP',
  'Última IP útil': 'Last usable IP',
  'Calcular': 'Calculate',
  'Prueba con un ejemplo': 'Try an example',
  'Red doméstica /24': 'Home network /24',
  'Oficina /22': 'Office /22',
  'Enlace punto a punto /30': 'Point-to-point link /30',
  'Copiar enlace': 'Copy link',
  'Guardar esta subred': 'Save this subnet',
  '192.168.1.10 o 192.168.1.10/24': '192.168.1.10 or 192.168.1.10/24',
  '24 o 255.255.255.0': '24 or 255.255.255.0',
  'ej. 10 - Ventas': 'e.g. 10 - Sales',
  'Puedes escribir el prefijo (24 o /24) o la máscara (255.255.255.0). También vale escribirlo todo junto en el campo de la IP: 192.168.1.10/24.': 'You can type the prefix (24 or /24) or the mask (255.255.255.0). You can also type it all together in the IP field: 192.168.1.10/24.',
  'Una etiqueta para reconocer esta subred cuando la guardes, por ejemplo 10 - Ventas. No cambia el cálculo.': 'A label to recognize this subnet once saved, for example 10 - Sales. It does not change the calculation.',
  'El gateway es la dirección del router de esa red, por donde salen los equipos hacia otras redes. Por costumbre suele ser la primera o la última dirección utilizable.': 'The gateway is the address of that network router, the way devices reach other networks. By convention it is usually the first or the last usable address.',
  'En pocas palabras': 'In a nutshell',
  'Máscara de subred': 'Subnet mask',
  'Dirección de red': 'Network address',
  'Dirección de broadcast': 'Broadcast address',
  'Rango de hosts útiles': 'Usable host range',
  'Total de direcciones': 'Total addresses',
  'Hosts utilizables': 'Usable hosts',
  'Clase IP': 'IP class',
  'Tipo': 'Type',
  'Privada (RFC 1918 / especial)': 'Private (RFC 1918 / special)',
  'Pública': 'Public',
  'Representación binaria': 'Binary representation',
  'Máscara': 'Mask',
  'Red': 'Network',
  'Equipos': 'Devices',
  'Bloque muy pequeño para GW + DHCP': 'Block too small for GW + DHCP',
  'Dividir': 'Split',
  'Abrir en el divisor visual': 'Open in the visual splitter',
  'Eliminar': 'Delete',
  'Quitar': 'Remove',
  'Clic para copiar': 'Click to copy',
  'Clic para volver a cargar esta subred': 'Click to reload this subnet',
  'Guardada': 'Saved',
  'Guardado': 'Saved',
  'Enlace copiado': 'Link copied',
  'Copia este enlace:': 'Copy this link:',
  '(primera IP)': '(first IP)',
  '(última IP)': '(last IP)',
  'Es una dirección privada o especial: funciona dentro de una red local, no se enruta en Internet.': 'It is a private or special address: it works inside a local network and is not routed on the Internet.',
  'Es una dirección pública: se puede enrutar en Internet.': 'It is a public address: it can be routed on the Internet.',
  'Esta "red" es una sola dirección (un equipo concreto).': 'This "network" is a single address (one specific device).',
  'Es un enlace punto a punto con 2 direcciones utilizables ({first} y {last}).': 'It is a point-to-point link with 2 usable addresses ({first} and {last}).',
  'Esta red admite {hosts} equipos, de {first} a {last}. La primera dirección ({network}) identifica la red y la última ({broadcast}) es el broadcast, así que no se asignan a equipos.': 'This network supports {hosts} devices, from {first} to {last}. The first address ({network}) identifies the network and the last one ({broadcast}) is the broadcast, so they are not assigned to devices.',
  'Tu IP {ip} pertenece a la red {net}/{prefix}. {hosts} {kind}': 'Your IP {ip} belongs to the network {net}/{prefix}. {hosts} {kind}',
  'Cómo se reparten los 32 bits: la máscara /{prefix} reserva {net} para la red y deja {hosts} para los equipos': 'How the 32 bits are split: the /{prefix} mask reserves {net} for the network and leaves {hosts} for devices',

  // ---- IPv4 input errors ----
  'Eso parece una dirección IPv6. Usa la pestaña "Calculadora IPv6".': 'That looks like an IPv6 address. Use the "IPv6 calculator" tab.',
  'Dirección IP inválida': 'Invalid IP address',
  'Debes indicar un prefijo CIDR o máscara': 'You must give a CIDR prefix or mask',
  'Máscara de subred inválida': 'Invalid subnet mask',
  'El prefijo CIDR debe estar entre 0 y 32': 'The CIDR prefix must be between 0 and 32',

  // ---- IPv6 ----
  'Plan guiado (empieza aquí)': 'Guided plan (start here)',
  'Calculadora': 'Calculator',
  '¿Primera vez con IPv6? En tres pasos obtienes un plan de direccionamiento listo para usar, sin necesidad de entender los prefijos de antemano.': 'New to IPv6? In three steps you get a ready-to-use addressing plan, with no need to understand prefixes beforehand.',
  'Lo mínimo que necesitas saber sobre IPv6': 'The bare minimum you need to know about IPv6',
  'Dirección:': 'Address:',
  'son 128 bits escritos en 8 grupos hexadecimales, por ejemplo': 'is 128 bits written as 8 hexadecimal groups, for example',
  '. Los': '. The',
  'abrevian grupos de ceros.': 'shorthand stands for runs of zeros.',
  'Prefijo (/48, /64…):': 'Prefix (/48, /64…):',
  'cuántos bits del inicio identifican la red. El resto identifica a los equipos dentro de ella.': 'how many of the leading bits identify the network. The rest identify the devices inside it.',
  'es el tamaño estándar de una LAN o VLAN. Aunque sea enorme (18 trillones de direcciones), es lo normal: no hay que ahorrar direcciones.': 'is the standard size of a LAN or VLAN. Even though it is huge (18 quintillion addresses), that is normal: there is no need to save addresses.',
  'lo que suele recibir un sitio completo. Contiene 65.536 redes /64, más que suficiente para dividirlo por VLAN.': 'what a whole site usually receives. It contains 65,536 /64 networks, more than enough to split it by VLAN.',
  'es el equivalente de las IPs privadas de IPv4 (192.168.x.x). Sirve para redes internas y laboratorio; no se enruta en Internet.': 'is the equivalent of IPv4 private IPs (192.168.x.x). It is for internal networks and labs; it is not routed on the Internet.',
  'Equipos:': 'Devices:',
  'normalmente se configuran solos (SLAAC o DHCPv6). No hay broadcast ni hace falta calcular rangos de hosts.': 'usually configure themselves (SLAAC or DHCPv6). There is no broadcast and no need to calculate host ranges.',
  '1. Tu prefijo base': '1. Your base prefix',
  'Red privada propia (ULA). Recomendado para empezar, laboratorio o red interna.': 'Your own private network (ULA). Recommended to get started, for labs or internal networks.',
  'Ya tengo un prefijo (de mi proveedor o de mi organización).': 'I already have a prefix (from my provider or my organization).',
  'Generar otro': 'Generate another',
  'Se genera al azar, así que es único para ti. Guárdalo: es tu identificador de red privada.': 'It is generated at random, so it is unique to you. Keep it: it is your private network identifier.',
  'Tu proveedor normalmente te da un /48 o un /56. Escríbelo con su prefijo, tal como te lo entregaron.': 'Your provider usually gives you a /48 or a /56. Type it with its prefix, exactly as it was given to you.',
  '2. Tus subredes (una por VLAN o red)': '2. Your subnets (one per VLAN or network)',
  '+ Agregar subred': '+ Add subnet',
  'Usar el número de VLAN como ID de subred (la VLAN 10 quedaría como': 'Use the VLAN number as the subnet ID (VLAN 10 would become',
  '3. Tamaño de cada subred': '3. Size of each subnet',
  'Tamaño de cada subred': 'Size of each subnet',
  '/64 · una LAN o VLAN (recomendado)': '/64 · one LAN or VLAN (recommended)',
  '/60 · hasta 16 LAN por cada subred': '/60 · up to 16 LANs per subnet',
  '/56 · hasta 256 LAN por cada subred': '/56 · up to 256 LANs per subnet',
  '/48 · un sitio completo por cada subred': '/48 · a whole site per subnet',
  'Si dudas, deja /64. Las funciones automáticas de IPv6 (SLAAC) requieren que cada LAN sea un /64.': 'If in doubt, leave /64. IPv6 automatic features (SLAAC) require every LAN to be a /64.',
  'Generar mi plan': 'Generate my plan',
  'Analiza cualquier dirección o prefijo IPv6 y divídelo en subredes más pequeñas.': 'Analyze any IPv6 address or prefix and split it into smaller subnets.',
  'Dirección IPv6 / prefijo': 'IPv6 address / prefix',
  'Red privada (ULA) /48': 'Private network (ULA) /48',
  'Oficina /56': 'Office /56',
  'Una LAN /64': 'One LAN /64',
  'Dividir en subredes de prefijo': 'Split into subnets of prefix',
  'Listar subredes': 'List subnets',
  'Subred': 'Subnet',
  'Primera dirección': 'First address',
  'Última dirección': 'Last address',
  'Nombre (ej. Usuarios)': 'Name (e.g. Users)',
  'Quitar esta subred': 'Remove this subnet',
  'Qué significa este prefijo': 'What this prefix means',
  'Dirección (comprimida)': 'Address (compressed)',
  'Dirección (expandida)': 'Address (expanded)',
  'Prefijo': 'Prefix',
  'Subredes /64 contenidas': '/64 subnets contained',
  'Cómo se reparten los 128 bits': 'How the 128 bits are split',
  'Cómo se reparten los 128 bits de cada dirección': 'How the 128 bits of each address are split',
  'Subredes': 'Subnets',
  'Tu prefijo base': 'Your base prefix',
  'Uso': 'Usage',
  'Nombre': 'Name',
  'Direcciones': 'Addresses',
  'Los equipos de cada subred suelen recibir su dirección automáticamente (SLAAC o DHCPv6), así que no hace falta repartir rangos a mano. El gateway sugerido es la primera dirección de cada subred.': 'The devices in each subnet usually get their address automatically (SLAAC or DHCPv6), so there is no need to hand out ranges. The suggested gateway is the first address of each subnet.',
  'Bloque muy grande, propio de un proveedor u organización enorme': 'Very large block, typical of a provider or a huge organization',
  'Bloque de una organización grande o de un proveedor pequeño': 'Block of a large organization or a small provider',
  'Un sitio completo: contiene 65.536 redes /64': 'A whole site: it contains 65,536 /64 networks',
  'Una parte de un sitio (varios miles de redes /64)': 'Part of a site (several thousand /64 networks)',
  'Una oficina u hogar: contiene 256 redes /64': 'An office or home: it contains 256 /64 networks',
  'Unas pocas redes /64': 'A few /64 networks',
  'Una LAN o VLAN. Es el tamaño estándar para equipos normales': 'A LAN or VLAN. It is the standard size for normal devices',
  'Más pequeño que una LAN normal: la autoconfiguración (SLAAC) no funciona aquí': 'Smaller than a normal LAN: autoconfiguration (SLAAC) does not work here',
  'Una sola dirección (un equipo)': 'A single address (one device)',
  'No especificada (::/128)': 'Unspecified (::/128)',
  'Loopback (::1/128)': 'Loopback (::1/128)',
  'IPv4 mapeada (::ffff:0:0/96)': 'IPv4-mapped (::ffff:0:0/96)',
  'Unicast link-local (fe80::/10)': 'Link-local unicast (fe80::/10)',
  'Unicast local única - ULA (fc00::/7)': 'Unique local unicast - ULA (fc00::/7)',
  'Multicast (ff00::/8)': 'Multicast (ff00::/8)',
  'Documentación (2001:db8::/32)': 'Documentation (2001:db8::/32)',
  'Unicast global (2000::/3)': 'Global unicast (2000::/3)',
  'Reservada / sin asignar': 'Reserved / unassigned',
  'No escribiste prefijo, así que usé /64, el tamaño estándar de una LAN.': 'You did not type a prefix, so I used /64, the standard size of a LAN.',
  'El nuevo prefijo debe ser mayor que /{prefix} y a lo sumo /128': 'The new prefix must be greater than /{prefix} and at most /128',
  'Solo se pueden listar divisiones de hasta 64 bits de diferencia': 'Only splits up to 64 bits apart can be listed',
  'Tu prefijo base: {msg}': 'Your base prefix: {msg}',
  'El tamaño de cada subred (/{size}) debe ser más pequeño que tu prefijo base (/{base}). Elige otro tamaño arriba o usa un prefijo base más grande.': 'The size of each subnet (/{size}) must be a smaller network than your base prefix (/{base}). Choose another size above or use a larger base prefix.',
  'Subred {n}': 'Subnet {n}',
  'Agrega al menos una subred.': 'Add at least one subnet.',
  'Para usar el número de VLAN como ID de subred, todas las filas necesitan una VLAN entre 1 y 4094 (o desmarca esa opción).': 'To use the VLAN number as the subnet ID, every row needs a VLAN between 1 and 4094 (or untick that option).',
  'Hay números de VLAN repetidos.': 'There are repeated VLAN numbers.',
  'No caben: con /{prefix} solo hay {cap} subredes /{size}. Usa un prefijo base más grande o un tamaño de subred más pequeño.': 'They do not fit: with /{prefix} there are only {cap} /{size} subnets. Use a larger base prefix or a smaller subnet size.',
  '{n} de {cap} subredes /{size} ({pct} %)': '{n} of {cap} /{size} subnets ({pct} %)',
  '{count} subredes /{prefix} en total': '{count} /{prefix} subnets in total',
  ' (se muestran las primeras {max})': ' (showing the first {max})',
  'Usuarios': 'Users',
  'Servidores': 'Servers',
  'Invitados': 'Guests',

  // ---- IPv6 input errors ----
  'Escribe una dirección IPv6': 'Type an IPv6 address',
  'IPv4 incrustada inválida': 'Invalid embedded IPv4',
  'Una dirección IPv6 solo puede tener un "::"': 'An IPv6 address can only have one "::"',
  'Demasiados grupos para usar "::"': 'Too many groups to use "::"',
  'Una dirección IPv6 necesita 8 grupos': 'An IPv6 address needs 8 groups',
  'Grupo inválido: "{g}"': 'Invalid group: "{g}"',
  'Indica el prefijo, por ejemplo 2001:db8::/32': 'Give the prefix, for example 2001:db8::/32',
  'El prefijo debe estar entre 0 y 128': 'The prefix must be between 0 and 128',

  // ---- Tools ----
  'Utilidades rápidas de IPv4.': 'Quick IPv4 utilities.',
  '¿Esta IP pertenece a la red?': 'Does this IP belong to the network?',
  'Comprobar': 'Check',
  'Convertidor de máscara / wildcard / CIDR': 'Mask / wildcard / CIDR converter',
  'Convertir': 'Convert',
  'Resumen de rutas (agregación)': 'Route summarization (aggregation)',
  'Resumir': 'Summarize',
  'Detección de traslapes': 'Overlap detection',
  'Buscar traslapes': 'Find overlaps',
  'Cargar subredes guardadas': 'Load saved subnets',
  'IP, ej. 10.1.2.3': 'IP, e.g. 10.1.2.3',
  'Red, ej. 10.0.0.0/8': 'Network, e.g. 10.0.0.0/8',
  '/24, 255.255.255.0 o 0.0.0.255': '/24, 255.255.255.0 or 0.0.0.255',
  'Una red por línea 192.168.0.0/24 192.168.1.0/24': 'One network per line\n192.168.0.0/24\n192.168.1.0/24',
  'Una red por línea (con etiqueta opcional) 10.0.0.0/16 Oficinas 10.0.5.0/24 Voz': 'One network per line (optional label)\n10.0.0.0/16 Offices\n10.0.5.0/24 Voice',
  'Resultado': 'Result',
  'Sí, pertenece a la red': 'Yes, it belongs to the network',
  'No pertenece a la red': 'It does not belong to the network',
  'Rango': 'Range',
  'Posición en la red': 'Position in the network',
  'Prefijo CIDR': 'CIDR prefix',
  'Direcciones totales': 'Total addresses',
  'Entradas': 'Entries',
  'Rutas resumidas': 'Summarized routes',
  'Supernet único que las cubre': 'Single supernet that covers them',
  'Direcciones en el supernet': 'Addresses in the supernet',
  'Direcciones en las rutas resumidas': 'Addresses in the summarized routes',
  'Las redes se resumen exactamente en una sola ruta.': 'The networks summarize exactly into a single route.',
  'Usar el supernet único incluiría direcciones que no estaban en tu lista; las rutas resumidas de arriba son exactas.': 'Using the single supernet would include addresses that were not in your list; the summarized routes above are exact.',
  'Traslapes encontrados': 'Overlaps found',
  'Dirección inválida: "{text}"': 'Invalid address: "{text}"',
  'Prefijo inválido en "{text}"': 'Invalid prefix in "{text}"',
  'Escribe al menos una red (una por línea)': 'Type at least one network (one per line)',
  'El prefijo debe estar entre 0 y 32': 'The prefix must be between 0 and 32',
  'No es una máscara ni un wildcard válido (los bits deben ser contiguos)': 'It is not a valid mask or wildcard (the bits must be contiguous)',
  'Escribe un prefijo (/24), una máscara (255.255.255.0) o un wildcard (0.0.0.255)': 'Type a prefix (/24), a mask (255.255.255.0) or a wildcard (0.0.0.255)',
  'No hay subredes guardadas en la calculadora todavía.': 'There are no saved subnets in the calculator yet.',
  'Escribe al menos dos redes (una por línea) para compararlas': 'Type at least two networks (one per line) to compare them',
  'es idéntica a': 'is identical to',
  'contiene a': 'contains',
  'está contenida en': 'is contained in',
  'se traslapa con': 'overlaps with',
  'Sin traslapes entre las {n} redes.': 'No overlaps among the {n} networks.',

  // ---- VLSM planner ----
  'Dile a la app cuántos equipos necesita cada red y calculará el tamaño exacto de cada subred, acomodándolas sin traslapes (VLSM). Después puedes sacar la configuración lista para tus equipos.': 'Tell the app how many devices each network needs and it will work out the exact size of each subnet, fitting them without overlaps (VLSM). Then you can get ready-to-use configuration for your devices.',
  'Red base': 'Base network',
  'Modo': 'Mode',
  'Estándar': 'Standard',
  'Margen de crecimiento': 'Growth margin',
  'Ninguno': 'None',
  '100 % (el doble)': '100 % (double)',
  'Redes que necesitas': 'Networks you need',
  '+ Agregar red': '+ Add network',
  'Calcular plan': 'Calculate plan',
  'La red grande de la que se reparten todas las subredes, por ejemplo 10.10.0.0 con prefijo 22.': 'The large network all the subnets are carved from, for example 10.10.0.0 with prefix 22.',
  'El prefijo indica cuántos bits del inicio de la IP identifican la red. Por ejemplo /24 equivale a la máscara 255.255.255.0 y deja 254 direcciones para equipos. Cuanto mayor es el número, más pequeña es la red.': 'The prefix says how many of the leading bits of the IP identify the network. For example /24 equals the mask 255.255.255.0 and leaves 254 addresses for devices. The larger the number, the smaller the network.',
  'Estándar sirve para redes locales. AWS, Azure y OCI reservan más direcciones en cada subred y tienen un tamaño mínimo, así que los equipos disponibles cambian.': 'Standard is for local networks. AWS, Azure and OCI reserve more addresses in each subnet and have a minimum size, so the available devices change.',
  'Espacio extra por si tu red crece. Con 25 %, una red de 100 equipos se planifica como si fueran 125.': 'Extra room in case your network grows. With 25 %, a network of 100 devices is planned as if it had 125.',
  'Nombre (ej. Ventas)': 'Name (e.g. Sales)',
  'Quitar esta red': 'Remove this network',
  'Administración': 'Administration',
  'Usado': 'Used',
  'Espacio libre': 'Free space',
  'ninguno': 'none',
  'Uso de la red base': 'Base network usage',
  'Libre': 'Free',
  'Pedidos': 'Requested',
  'Capacidad': 'Capacity',
  'Rango utilizable': 'Usable range',
  'Abrir en el divisor': 'Open in the splitter',
  'Configuración para equipos': 'Device configuration',
  'En AWS, Azure y OCI las subredes se crean desde la consola, la CLI o Terraform con su bloque CIDR (columna "Subred"), y el gateway y el DHCP los gestiona la nube. Por eso aquí solo se genera configuración en modo Estándar.': 'In AWS, Azure and OCI the subnets are created from the console, the CLI or Terraform with their CIDR block ("Subnet" column), and the cloud manages the gateway and DHCP. That is why configuration is only generated here in Standard mode.',
  'Copiar configuración': 'Copy configuration',
  'Fabricante': 'Vendor',
  'Los textos entre < > (interfaz, VLAN sin definir) son datos que debes completar. Revisa siempre la configuración antes de aplicarla.': 'The texts between < > (interface, undefined VLAN) are values you must fill in. Always review the configuration before applying it.',
  'Las redes se ordenan de la más grande a la más pequeña para que encajen sin dejar huecos.': 'Networks are sorted from largest to smallest so they fit without leaving gaps.',
  ' Cada red incluye una dirección extra para el gateway.': ' Each network includes one extra address for the gateway.',
  ' Incluye {n} % de margen de crecimiento.': ' Includes {n} % growth margin.',
  '{used} de {total} direcciones ({pct} %)': '{used} of {total} addresses ({pct} %)',
  '{pct} % · {n} direcciones': '{pct} % · {n} addresses',
  'Red {n}': 'Network {n}',
  'La red base no es una dirección IPv4 válida.': 'The base network is not a valid IPv4 address.',
  'El prefijo base debe estar entre 0 y 30.': 'The base prefix must be between 0 and 30.',
  '"{name}": escribe cuántos equipos necesita (un número mayor que 0).': '"{name}": type how many devices it needs (a number greater than 0).',
  'Agrega al menos una red.': 'Add at least one network.',
  'No caben: necesitas {needed} direcciones y /{prefix} solo tiene {have} (faltan {short}). Usa un prefijo base más grande, por ejemplo /{suggested}, o pide menos equipos.': 'They do not fit: you need {needed} addresses and /{prefix} only has {have} ({short} missing). Use a larger base prefix, for example /{suggested}, or ask for fewer devices.',
  'Escribe cuántos equipos necesita cada red y te sugiero qué prefijo base usar.': 'Type how many devices each network needs and I will suggest which base prefix to use.',
  'Con /{prefix} no caben: tus redes necesitan {total} direcciones y necesitas al menos /{needed} (cuanto más pequeño el número, más grande la red).': 'With /{prefix} they do not fit: your networks need {total} addresses and you need at least /{needed} (the smaller the number, the larger the network).',
  '/{prefix} es justo lo necesario: usarías el {pct} % ({total} direcciones). Si esperas crecer, considera /{bigger}.': '/{prefix} is just what you need: you would use {pct} % ({total} addresses). If you expect growth, consider /{bigger}.',
  '/{prefix} deja margen para crecer: usarías el {pct} % ({total} de {cap} direcciones).': '/{prefix} leaves room to grow: you would use {pct} % ({total} of {cap} addresses).',
  '/{prefix} es mucho más grande de lo necesario: solo usarías el {pct} % ({total} direcciones). Con /{needed} alcanza; deja /{prefix} solo si planeas crecer mucho.': '/{prefix} is much larger than needed: you would use only {pct} % ({total} addresses). /{needed} is enough; keep /{prefix} only if you plan to grow a lot.',
  'Usar /{n}': 'Use /{n}',
  'Enviadas ({n})': 'Sent ({n})',
  'Ya estaban': 'Already there',

  // ---- Visual splitter ----
  'Define una red base y divide o une bloques haciendo clic — como un árbol binario de subredes.': 'Define a base network and split or join blocks by clicking — like a binary tree of subnets.',
  'Generar': 'Generate',
  'Reiniciar': 'Reset',
  'Guardar proyecto': 'Save project',
  'Proyectos guardados…': 'Saved projects…',
  'Proyectos guardados': 'Saved projects',
  'Nombre del proyecto': 'Project name',
  'Cargar': 'Load',
  'Subred (CIDR)': 'Subnet (CIDR)',
  'Rango de direcciones': 'Address range',
  'IPs utilizables': 'Usable IPs',
  'Nota': 'Note',
  'Clic: dividir / unir': 'Click: split / join',
  'Imagen': 'Image',
  'Copiar imagen': 'Copy image',
  'Descargar PNG (alta calidad)': 'Download PNG (high quality)',
  'Descargar SVG (vectorial)': 'Download SVG (vector)',
  'Datos': 'Data',
  'Copiar tabla': 'Copy table',
  'Exportar CSV': 'Export CSV',
  'Enviar a calculadora': 'Send to calculator',
  'Compartir enlace': 'Share link',
  'Clic para dividir esta subred': 'Click to split this subnet',
  'Clic para unir esta subred': 'Click to join this subnet',
  'Tamaño mínimo del modo: /{n}': 'Minimum size for this mode: /{n}',
  'Estándar: subred mínima /32. Dos direcciones reservadas por subred de tamaño <= /30: red (network + 0) y broadcast (última dirección).': 'Standard: minimum subnet /32. Two reserved addresses per subnet of size <= /30: network (network + 0) and broadcast (last address).',
  'AWS: subred mínima /28. Cinco direcciones reservadas por subred: red (network + 0), router de la VPC, DNS de la VPC, uso futuro y broadcast (última dirección).': 'AWS: minimum subnet /28. Five reserved addresses per subnet: network (network + 0), VPC router, VPC DNS, future use and broadcast (last address).',
  'Azure: subred mínima /29. Cinco direcciones reservadas por subred: red (network + 0), gateway por defecto, dos de mapeo DNS y broadcast (última dirección).': 'Azure: minimum subnet /29. Five reserved addresses per subnet: network (network + 0), default gateway, two DNS mappings and broadcast (last address).',
  'OCI: subred mínima /30. Tres direcciones reservadas por subred: red (network + 0), gateway por defecto (network + 1) y broadcast (última dirección).': 'OCI: minimum subnet /30. Three reserved addresses per subnet: network (network + 0), default gateway (network + 1) and broadcast (last address).',
  'Este nodo tiene {n} subredes debajo. ¿Unirlas todas en una sola?': 'This node has {n} subnets below it. Join them all into one?',
  'Escribe un nombre para guardar el proyecto': 'Type a name to save the project',
  'Elige un proyecto de la lista': 'Choose a project from the list',
  'No se pudo cargar el proyecto (datos inválidos)': 'The project could not be loaded (invalid data)',
  '¿Eliminar el proyecto "{name}"?': 'Delete the project "{name}"?',
  'Copiada': 'Copied',
  'Descargado': 'Downloaded',
  'Imagen copiada': 'Image copied',
  'No se pudo copiar al portapapeles': 'Could not copy to the clipboard',
  'Tu navegador no permite copiar imágenes. Usa "Descargar PNG".': 'Your browser does not allow copying images. Use "Download PNG".',
  'No se pudo copiar la imagen ({err}). Usa "Descargar PNG".': 'The image could not be copied ({err}). Use "Download PNG".',
  'Dirección IP base inválida': 'Invalid base IP address',
  'El prefijo base debe estar entre 0 y {n}': 'The base prefix must be between 0 and {n}',
  'Esto eliminará todas las divisiones. ¿Continuar?': 'This will remove all the splits. Continue?',
  'La red base /{prefix} es más pequeña que el mínimo de {mode} (/{limit}). Genera una red más grande primero.': 'The base network /{prefix} is smaller than the minimum for {mode} (/{limit}). Generate a larger network first.',
  'El modo {mode} no permite subredes menores a /{limit}. Se unirán las divisiones más pequeñas. ¿Continuar?': 'The {mode} mode does not allow subnets smaller than /{limit}. The smallest splits will be joined. Continue?',
  'Segmentación {cidr}': 'Segmentation {cidr}',
  'Modo {mode} · {n} subredes · {date}': 'Mode {mode} · {n} subnets · {date}',
  'Árbol de subredes': 'Subnet tree',
  'Primera IP útil (CSV)': 'First usable IP',
  'Generado con SubnetCraft': 'Generated with SubnetCraft',
  'El navegador no pudo generar una imagen tan grande. Usa la opción SVG.': 'The browser could not generate such a large image. Use the SVG option.',

  '<INTERFAZ_TRONCAL>': '<TRUNK_INTERFACE>',
  '<INTERFAZ_FISICA>': '<PHYSICAL_INTERFACE>',

  // ---- Misc ----
  'Copiado: {text}': 'Copied: {text}',
  'No se pudo copiar': 'Could not copy',
};
